version = 1

test_patterns = [
  "tests/**",
  "**_test.**"
]

exclude_patterns = ["**/mock/**", "docs/**", "**/public/**,", "**/dist/**"]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["vue"]
  environment = ["nodejs", "browser", "vitest"]
  module_system = "es-modules"
  dialect = "typescript"

[[transformers]]
name = "prettier"
