version = 1

test_patterns = [
  "tests/**",
  "**_test.**"
]

exclude_patterns = ["**/mock/**"]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["vue"]

[[transformers]]
name = "prettier"